name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
template: |
  # What's Changed (testing)
  
  $CHANGES
categories:
  - title: ⚠️ Breaking API changes
    label: type/breaking-api-change
  - title: 🚀 Features & Enhancements
    labels:
      - type/feature
      - type/enhancement
  - title: ☠️ Deprecations
    label: type/deprecation
  - title: 🐛 Bug Fixes
    label: type/bug
  - title: 📖 Documentation
    label: type/docs
  - title: 🧹 Housekeeping
    labels:
      - type/housekeeping
      - type/test-improvement
  - title: 📦 Dependency updates
    label: dependencies
    collapse-after: 5