name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  CodeAudits:
    uses: evanchooly/workflows/.github/workflows/code-audits.yml@master

  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      saveBuild: true
      archive-name: "graven-first-build"

  Test:
    needs:
      - CodeAudits
      - Build
    strategy:
      matrix:
        gradle: [ 14, 8.2.1, 8.1.1, 8.0.2, 7.6.2, 7.5, 7.4.2, 7.3.3, 7.2, 7.1.1, 7.0.2 ]
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      reuseBuild: true
      maven-flags: "-Dgradle.version=${{ matrix.gradle }}"
      archive-name: "graven-${{ matrix.gradle }}"

  Release:
    if: github.ref_type == 'branch' || github.ref_type == 'tag'
    needs:
      - Build
      - Test
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    with:
      java: 17
    secrets:
      GH_PUSH_TOKEN       : ${{ secrets.GH_PUSH_TOKEN }}
      GPG_PASSPHRASE      : ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY     : ${{ secrets.GPG_PRIVATE_KEY }}
      SONATYPE_USERNAME   : ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD   : ${{ secrets.SONATYPE_PASSWORD }}
