name: Build Project

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  CodeAudits:
    uses: evanchooly/workflows/.github/workflows/code-audits.yml@master

  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      saveBuild: true

  Test:
    needs:
      - CodeAudits
      - Build
    strategy:
      fail-fast: false
      matrix:
        gradle: [ 8.3, 8.2.1, 8.1.1, 8.0.2, 7.6.2 ]
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      reuseBuild: true
      maven-flags: "-Dgradle.version=${{ matrix.gradle }}"
      archive-name: "graven-${{ matrix.gradle }}"

  Release:
    if: github.ref_type == 'branch' || github.ref_type == 'tag'
    needs:
      - Build
      - Test
    uses: evanchooly/workflows/.github/workflows/jreleaser.yml@master
    secrets:
      GH_PUSH_TOKEN       : ${{ secrets.GH_PUSH_TOKEN }}
      GPG_PASSPHRASE      : ${{ secrets.GPG_PASSPHRASE }}
      GPG_PUBLIC_KEY      : ${{ secrets.GPG_PUBLIC_KEY }}
      GPG_PRIVATE_KEY     : ${{ secrets.GPG_PRIVATE_KEY }}
      SONATYPE_USERNAME   : ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD   : ${{ secrets.SONATYPE_PASSWORD }}
